### ISSUE TITLE
ERROR in BreadcrumbsModule is not an NgModule

### ISSUE THREAD

**Issue by gholighelgheli** [Centroida/ng4-breadcrumbs#1]
@Centroida
hi
when I use ng serve command, there is an error:
ERROR in BreadcrumbsModule is not an NgModule

but after i save the document it compiles and serves the app eithout any problem. and the module works correctly.
now the problem is that when i use ng build command , the error appears and there is no way to get rid of this and compile the app. i also tried reinstalling the module using npm install --save .. but it doesn't work.
how can i handle it?
is it related to the version on angular cli i am using or what? (currently 
"@angular/cli": "1.2.0",
"@angular/compiler-cli" : "^4.0.0", )

thanks

**Comment by Kaizeras** [comment]
Hello @gholighelgheli , I will look into the issue ASAP.

 It's probably due to deprecated dependencies.

**Comment by gholighelgheli** [comment]
Thanks @Kaizeras.
please let me know about the solution you probably found.

**Comment by bhushangahire** [comment]
+1

**Comment by Kaizeras** [comment]
Fixed in [0.1.25](https://github.com/Centroida/ng4-breadcrumbs/releases) .
