### ISSUE TITLE
Weird breadcrumbs when Lazy Loading Routes

### ISSUE THREAD

**Issue by j-nguyen** [Centroida/ng4-breadcrumbs#5]
When you attempt to lazy-load the routes, it gives out multiple breadcrumbs.

For example:

```js
const routes: Routes = [
  {path: 'users', loadChildren: './user/user.module#UserModule'}
]
```

I can try helping out in this scenario. I believe that the `ActivatedRoute` doesn't get activated quite yet, and outputs out an empty route.

**Comment by stndrs** [comment]
I've also got lazy loaded routes, and I think I'm getting the same issue. The breadcrums looks like:
```
empty_breadcrumb_name \ empty_breadcrumb_name \ empty_breadcrumb_name \ [Current Route]
```
