### ISSUE TITLE
github.io demo does not work

### ISSUE THREAD

**Issue by viggyprabhu** [Centroida/ng4-breadcrumbs#7]
the link given in README does not work. Please fix the same so that we can view a demo.

**Comment by yavulan** [comment]
Looks like still reproducing:
https://centroida.github.io/ng4-breadcrumbs/ returns 404

**Comment by ZendyLim** [comment]
Can we reopen this
Still returns 404

**Comment by marquesgabriel** [comment]
Leaving this comment to add that still returns 404
